site_name: GianDocs
site_description: 'A Material Design theme for MkDocs'
site_author: 'Giancarlos Salas'
repo_url: 'https://github.com/giansalex/mkdocs-sample'
pages:
    - Home: index.md
    - About: about.md
    - Code: code.md
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'Teal'
    accent: 'Indigo'

extra_css:
  - 'css/prism.css'
extra_javascript:
  - js/prism.js

extra:
  social:
    - type: 'github'
      link: 'https://github.com/giansalex'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
